title: Linux 101
email: your-email@example.com

description: >- 
  The "Linux 101" is an introductory course in Computer Science that covers
  basics of Operating Systems, different aspects of system programming using C,
  practical coding tasks and more.

baseurl: /linux101 
url: https://davitp.github.io 
domain: davitp.github.io 

twitter_username: davit_pet
github_username:  davitp

# More links
aux_links:
  "Edit on Github":
    - "//github.com/davitp/linux101"

# Build settings
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-feed
